pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/sebmunoz98/Cronoface_Cerradura.git'
            }
        }

        stage('Instalar PlatformIO') {
            steps {
                bat 'pip install platformio'
            }
        }

        stage('Verificar PlatformIO') {
            steps {
                bat 'pio --version'
            }
        }

        stage('Compilar ESP32') {
            steps {
                dir('Cronoface') {
                    bat 'pio run'
                }
            }
        }
    }
}
}
